src/Entity/Demand.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\DemandRepository")
 */
class Demand
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\File(
     *     mimeTypes = {"image/jpeg", "image/png", "application/pdf"},
     *     mimeTypesMessage="Veuillez selectionner fichier au format .PDF, .PNG ou .JPEG")
     */
    private $certificate;

    /**
     * @ORM\Column(type="integer")
     */
    private $nb_certificate;

    /**
     * @ORM\Column(type="date")
     * @Assert\Date()
     */
    private $certificate_date;

    /**
     * @ORM\Column(type="datetime")
     */
    private $submit_date;


    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    public function getId()
    {
        return $this->id;
    }

    public function getCertificate(): ?string
    {
        return $this->certificate;
    }

    public function setCertificate(string $certificate): self
    {
        $this->certificate = $certificate;

        return $this;
    }

    public function getNbCertificate(): ?int
    {
        return $this->nb_certificate;
    }

    public function setNbCertificate(int $nb_certificate): self
    {
        $this->nb_certificate = $nb_certificate;

        return $this;
    }

    public function getCertificateDate(): ?\DateTimeInterface
    {
        return $this->certificate_date;
    }

    public function setCertificateDate(\DateTimeInterface $certificate_date): self
    {
        $this->certificate_date = $certificate_date;

        return $this;
    }

    public function getSubmitDate(): ?\DateTimeInterface
    {
        return $this->submit_date;
    }

    public function setSubmitDate(\DateTimeInterface $submit_date): self
    {
        $this->submit_date = $submit_date;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }
}

src/Form/DemandType.php
<?php
/**
 * Created by PhpStorm.
 * User: romain
 * Date: 26/08/18
 * Time: 12:22
 */

namespace App\Form;

use App\Entity\Demand;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class DemandType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nb_certificate', NumberType::class, ['label' => "Numéro d'état"])
            ->add('certificate_date', DateType::class, [
                'label' => "Date d'obtention",
                'attr' => [
                    'class' => 'datepicker'
                ],
                'widget' => 'single_text',
                'format' => 'dd/MM/yyyy',
            ])
            ->add('certificate', FileType::class, [
                'label' => "Copie de l'attestation",
                'help' => '*Format acceptés: JPG, PNG, PDF'
            ])
            ->add('submit', SubmitType::class, ['label' => 'Envoyer la demande']);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Demand::class,
        ]);
    }
}

src/Controller/DemandController.php
<?php
/**
 * Created by PhpStorm.
 * User: romain
 * Date: 25/08/18
 * Time: 16:11
 */

namespace App\Controller;

use App\Entity\Demand;
use App\Form\CertifyType;
use App\Form\DemandType;
use App\Service\BreadcrumbManager;
use App\Service\DemandManager;
use App\Service\PaginationManager;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class DemandController extends Controller
{
    const NBR_ARTICLE_DEMAND = 3;

    const PAGINATION_DISPLAY_DEMAND = 5;

    /**
     * @Route("/profil/demande", name="demand")
     * @param Request $request
     * @param DemandManager $demandManager
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|\Symfony\Component\HttpFoundation\Response
     */
    public function demandAction(Request $request, DemandManager $demandManager){
        //Breadcrumb
        $breadcrumb = new BreadcrumbManager();
        $breadcrumb
            ->add('profil', 'Mon profil')
            ->add('demand', 'Demande naturaliste');

        $demand = new Demand();
        $form = $this->createForm(DemandType::class, $demand);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $demandManager->uploadFile($demand, $form->get('certificate')->getData());
            $demandManager->setDefaultDemand($demand);
            $this->addFlash('success', 'Demande envoyé');
//            return $this->redirectToRoute('profil');
        }

        $alreadySubmit= $this->getDoctrine()
            ->getRepository(Demand::class)
            ->countByID($this->getUser()->getId());

        if($alreadySubmit > 0){
            return $this->render('demand/alreadySubmit.html.twig', [
                'breadcrumb' => $breadcrumb->getBreadcrumb()
            ]);
        }

        return $this->render('demand/demand.html.twig', [
            'form' => $form->createView(),
            'breadcrumb' => $breadcrumb->getBreadcrumb()
        ]);
    }

    /**
     * @Route("/profil/naturalistes-attente/{page}", name="waiting-demand", requirements={"page"="\d+"})
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function waitingDemandAction($page = 1){
        //Breadcrumb
        $breadcrumb = new BreadcrumbManager();
        $breadcrumb
            ->add('profil', 'Mon profil')
            ->add('waiting-demand', 'Demande naturaliste');

        $demands = $this->getDoctrine()
            ->getRepository(Demand::class)
            ->findWithOffset(($page-1)*self::NBR_ARTICLE_DEMAND,self::NBR_ARTICLE_DEMAND);

        $nbreDemand = $this->getDoctrine()
            ->getRepository(Demand::class)
            ->getNumberDemand();

        $pagination = new PaginationManager($page,$nbreDemand,self::NBR_ARTICLE_DEMAND,self::PAGINATION_DISPLAY_DEMAND, 'waiting-demand');

        return $this->render('demand/waitingDemand.html.twig', [
            'breadcrumb' => $breadcrumb->getBreadcrumb(),
            'demands' => $demands,
            'pagination' => $pagination
        ]);
    }

    /**
     * @Route("/profil/certification/{id}", name="certify-demand", requirements={"id"="\d+"})
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function cetifyDemandAction($id, Request $request, DemandManager $demandManager){

        $demand = $this->getDoctrine()
            ->getRepository(Demand::class)
            ->findById($id);

        $form = $this->createForm(CertifyType::class, $demand);
        $form->handleRequest($request);

        if($form->isSubmitted()){
            if ($form->getClickedButton()->getName() == 'accept'){
                $demandManager->certified($demand);
            }
            elseif ($form->getClickedButton()->getName() == 'decline'){
                $demandManager->decline($demand);
            }
            $demandManager->deleteDemand($demand);
            return $this->redirectToRoute('waiting-demand');
        }

        return $this->render('demand/certifyDemand.html.twig', [
            'form' => $form->createView(),
            'demand' => $demand
        ]);
    }
}

templates/demand/alreadySubmit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Demande naturaliste - NAO{% endblock %}

{% block body %}
    {{ include('common/header.html.twig', {'title' : 'Demande naturaliste'}) }}
    {{ include('common/breadcrumb.html.twig', {'breadcrumb' : breadcrumb }) }}
    <div class="container">
        <div class="row only-one-block">
            <p class="col s12 center">
                Votre demande a bien été envoyé et est en cour de vérification
            </p>
        </div>
    </div>
{% endblock %}

templates/demand/certifyDemand.html.twig
{% extends 'base.html.twig' %}
{% form_theme form 'materialize_layout.html.twig' %}

{% block title %}Demande naturaliste - NAO{% endblock %}

{% block body %}
    <div class="grey lighten-3">
        <div class="container">
            <div class="row">
                <div class="col s12 m8 offset-m2 xl6 offset-xl3">
                    <div class="row center">
                        <div class="col s10 offset-s1 m6 offset-m3 xl6 offset-xl3">
                            <img src="{% if demand.user.image is null%}{{ asset('assets/img/profile-placeholder.jpg') }}{% else %}{{ image_profile_directory }}/{{ demand.user.image }}{% endif %}" alt="photo_profil" class="responsive-img circle">
                        </div>
                    </div>
                    <div class="row center margin-b margin-t title-certify">
                        {{ demand.user.lastname|upper }} {{ demand.user.firstname }}
                    </div>
                    <div class="row padding-15 border-teal white link-teal">
                        <p><b>Numéro d'état :</b> {{ demand.nbCertificate }}</p>
                        <p><b>Date d'obtention :</b> {{ demand.certificateDate|date("d/m/Y") }}</p>
                        <p><b>Copie de l'attestation :</b> <a href="{{ demand_file_directory }}/{{ demand.certificate }}" target="_blank">Lien</a></p>
                    </div>
                </div>
                {{ form_start(form) }}
                <div class="col s12">
                    <div class="center margin-t margin-b">
                        <a href="#modal_accept" class="btn-round btn btn-brown modal-trigger">Valider la demande</a>
                        <a href="#modal_decline" class="btn-round btn btn-brown modal-trigger">Refuser</a>
                    </div>
                </div>

                <div id="modal_accept" class="modal">
                    <div class="modal-content">
                        <p class="center">Voulez vous vraiment certifier ce dossier ?</p>
                    </div>
                    <div class="modal-footer">
                        {{ form_widget(form.accept, { 'attr' : { 'class' : 'btn-round btn-teal'}}) }}
                        <a href="#" class="modal-close btn btn-flat btn-round">Annuler</a>
                    </div>
                </div>

                <div id="modal_decline" class="modal">
                    <div class="modal-content">
                        <p class="center">Voulez-vous vraiment refuser ce dossier ?</p>
                    </div>
                    <div class="modal-footer">
                        {{ form_widget(form.decline, { 'attr' : { 'class' : 'btn-round btn-teal'}}) }}
                        <a href="#" class="modal-close btn btn-flat btn-round">Annuler</a>
                    </div>
                </div>
                {{ form_end(form) }}

            </div>
        </div>
    </div>
{% endblock %}
{% block javascripts %}
    {{ parent() }}
    <script>
        $(document).ready(function(){
            $('.modal').modal();
        });
    </script>
{% endblock %}

templates/demand/demand.html.twig
{% extends 'base.html.twig' %}
{% form_theme form 'materialize_layout.html.twig' %}

{% block title %}Demande naturaliste - NAO{% endblock %}

{% block body %}
    {{ include('common/header.html.twig', {'title' : 'Demande naturaliste'}) }}
    {{ include('common/breadcrumb.html.twig', {'breadcrumb' : breadcrumb }) }}
    <div class="container">
        {{ form_start(form) }}
        <div class="row">
            <div class="col s12 l6">
                {{ form_row(form.nb_certificate) }}
            </div>
            <div class="col s12 l6">
                {{ form_row(form.certificate_date) }}
            </div>
        </div>
        {{ form_row(form.certificate) }}
        {{ form_help(form.certificate) }}

        <div class="row center margin-t margin-b">
            {{ form_widget(form.submit, { 'attr' : { 'class' : 'btn-round btn-brown'}}) }}
        </div>

        {{ form_end(form) }}
    </div>
{% endblock %}

templates/demand/waitingDemand.html.twig
{% extends 'base.html.twig' %}

{% block title %}Demande naturaliste - NAO{% endblock %}

{% block body %}
    {{ include('common/header.html.twig', {'title' : 'Demande naturaliste'}) }}
    {{ include('common/breadcrumb.html.twig', {'breadcrumb' : breadcrumb }) }}
    <div class="row container">
        {% for demand in demands %}
            <div class="col s12 l4">
                <div class="card">
                    <div class="card-image">
                        <img src="{% if demand.user.image is null%}{{ asset('assets/img/profile-placeholder.jpg') }}{% else %}{{ image_profile_directory }}/{{ demand.user.image }}{% endif %}" alt="photo_profil">
                    </div>
                    <div class="card-content center">
                        <div class="card-title">{{ demand.user.lastname|upper }} {{ demand.user.firstname }}</div>
                        <p>Demande envoyé le {{ demand.submitDate|date("d/m/Y") }}</p>
                    </div>
                    <div class="center card-action">
                        <a href="{{ path('certify-demand', {'id': demand.id}) }}" class="btn btn-round btn-teal">Voir plus</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    <div class="center-align">
        {{ include('common/pagination.html.twig', {'paginaion' : pagination}) }}
    </div>
{% endblock %}