src/Entity/Article.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ArticleRepository")
 */
class Article
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(max="255", groups={"whitout_image"})
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @ORM\Column(type="boolean")
     */
    private $status;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $publishing_date;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $modification_date;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\File(
     *     mimeTypes = {"image/jpeg", "image/png"},
     *     mimeTypesMessage="Veuillez sélectionner une image .PNG ou .JPEG")
     */
    private $image;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    public function getId()
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getStatus(): ?bool
    {
        return $this->status;
    }

    public function setStatus(bool $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getPublishingDate(): ?\DateTimeInterface
    {
        return $this->publishing_date;
    }

    public function setPublishingDate(?\DateTimeInterface $publishing_date): self
    {
        $this->publishing_date = $publishing_date;

        return $this;
    }

    public function getModificationDate(): ?\DateTimeInterface
    {
        return $this->modification_date;
    }

    public function setModificationDate(?\DateTimeInterface $modification_date): self
    {
        $this->modification_date = $modification_date;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }
}

src/Controller/BlogController.php
<?php
/**
 * Created by PhpStorm.
 * User: romain
 * Date: 06/08/18
 * Time: 22:17
 */



namespace App\Controller;

use App\Entity\Article;
use App\Form\AddArticleType;
use App\Form\ArticleType;
use App\Form\ArticleWhitoutImageType;
use App\Service\ArticleManager;
use App\Service\BreadcrumbManager;
use App\Service\PaginationManager;
use function Sodium\add;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;

class BlogController extends Controller
{
    const NBR_ARTICLE_BLOG = 6;
    const NBR_ARTICLE_MANAGE = 6;

    const PAGINATION_DISPLAY_BLOG = 5;
    const PAGINATION_DISPLAY_MANAGE = 5;

    /**
     * @return \Symfony\Component\HttpFoundation\Response
     * @Route("/amis-oiseaux-articles-blog-information/{page}", name="blog", requirements={"page"="\d+"})
     */
    public function blogAction($page = 1){

        //Requete BDD
        $repository = $this->getDoctrine()->getRepository(Article::class);
        $articles = $repository->findPublishedWithOffset(($page-1)*self::NBR_ARTICLE_BLOG,self::NBR_ARTICLE_BLOG);
        $nbreArticle = $repository->getNumberPublishedArticle();

        //Pagination
        $pagination =  new PaginationManager($page, $nbreArticle,self::NBR_ARTICLE_BLOG,self::PAGINATION_DISPLAY_BLOG, 'blog');

        //Breadcrumb
        $breadcrumb = new BreadcrumbManager();
        $breadcrumb
            ->add('blog', 'Blog');

        return $this->render('blog/index.html.twig', [
            'articles' => $articles,
            'pagination' => $pagination,
            'breadcrumb' => $breadcrumb->getBreadcrumb()
        ]);
    }

    /**
     * @return \Symfony\Component\HttpFoundation\Response
     * @Route("/blog/article/{id}", name="blog-article", requirements={"id"="\d+"})
     */
    public function articleAction($id){

        //Requete BDD
        $article = $this->getDoctrine()
            ->getRepository(Article::class)
            ->findPublishedById($id);

        //Breadcrumb
        $breadcrumb = new BreadcrumbManager();
        $breadcrumb
            ->add('blog', 'Blog')
            ->add('blog-article', 'Article', array('id' => $id));

        return $this->render('blog/article.html.twig', [
            'article' => $article,
            'breadcrumb' => $breadcrumb->getBreadcrumb()
        ]);
    }

    /**
     * @return \Symfony\Component\HttpFoundation\Response
     * @Route("/profil/gerer-articles/{page}", name="gerer-articles", requirements={"page"="\d+"})
     */
    public function manageBlogAction($page = 1, ArticleManager $articleManager, Request $request){

        //Requete BDD
        $articles = $this->getDoctrine()
            ->getRepository(Article::class)
            ->findWithOffset(($page-1)*self::NBR_ARTICLE_MANAGE, self::NBR_ARTICLE_MANAGE);

        //Formulaire
        $article = new Article();
        $form = $this->createForm(AddArticleType::class, $article);
        $form->handleRequest($request);

        if ($form->isSubmitted()) {
            $entityManager = $this->getDoctrine()->getManager();

            $entityManager->persist($articleManager->getDefaultArticle());
            $entityManager->flush();
            return $this->redirectToRoute('gerer-articles');
        }

        $nbreArticle = $this->getDoctrine()
            ->getRepository(Article::class)
            ->getNumberArticle();

        //Pagination
        $pagination =  new PaginationManager($page,$nbreArticle,self::NBR_ARTICLE_BLOG,self::PAGINATION_DISPLAY_BLOG, 'gerer-articles');

        //Breadcrumb
        $breadcrumb = new BreadcrumbManager();
        $breadcrumb
            ->add('profil', 'Mon profil')
            ->add('gerer-articles', 'Gérer les articles');

        return $this->render('blog/manageBlog.html.twig', [
            'form' => $form->createView(),
            'articles' => $articles,
            'pagination' => $pagination,
            'breadcrumb' => $breadcrumb->getBreadcrumb()
        ]);
    }

    /**
     * @return \Symfony\Component\HttpFoundation\Response
     * @Route("/profil/article/{id_article}", name="edit-article", requirements={"id_article"="\d+"})
     */
    public function editArticleAction(Request $request, ArticleManager $articleManager, $id_article){

        //Requete BDD
        $article = $this->getDoctrine()
            ->getRepository(Article::class)
            ->findById($id_article);

        $form = '';

        if($article->getImage() === null){
            $form = $this->createForm(ArticleType::class, $article);
        }
        else{
            $form = $this->createForm(ArticleWhitoutImageType::class, $article);
        }

        //Si l'article n'est pas publié, on ajoute le bouton 'Publier'
        if($article->getStatus() === false){
            $form->add('publish', SubmitType::class, ['label' => 'Publier article']);
        }

        //Autre boutons ajoutés
        $form->add('save', SubmitType::class, ['label' => 'Enregistrer'])
            ->add('delete', SubmitType::class, ['label' => 'Supprimer']);

        $form->handleRequest($request);

        //Si le formulaire est soumis et valide
        if ($form->isSubmitted() && $form->isValid()) {

            //Supprimer image
            if ($form->getClickedButton()->getName() == 'delete_image'){
                $articleManager->deleteImage($article);
                return $this->redirectToRoute('edit-article', ['id_article' => $id_article]);
            }

            else{

                //Upload l'image
                if ($article->getImage() !==  null && $form->has('image')){
                    $articleManager->uploadImage($article, $form->get('image')->getData());
                }

                //Action en fonction du bouton
                if ($form->getClickedButton()->getName() == 'delete'){
                    $articleManager->deleteArticle($article);
                }
                elseif ($form->getClickedButton()->getName() == 'save'){
                    $articleManager->saveArticle($article);
                }
                elseif ($form->getClickedButton()->getName() == 'publish'){
                    $articleManager->publishArticle($article);
                }
                return $this->redirectToRoute('gerer-articles');
            }
        }

        //Breadcrumb
        $breadcrumb = new BreadcrumbManager();
        $breadcrumb
            ->add('profil', 'Mon profil')
            ->add('gerer-articles', 'Article')
            ->add('edit-article', 'Editer article', array('id_article' => $id_article));

        return $this->render('blog/editArticle.html.twig', [
            'form' => $form->createView(),
            'breadcrumb' => $breadcrumb->getBreadcrumb()
        ]);
    }
}

templates/blog/article.html.twig
{% extends 'base.html.twig' %}

{% block title %}Article - NAO{% endblock %}

{% block body %}
    {% if article.image is null %}
        {% set image =  'http://via.placeholder.com/750x350' %}
    {% else %}
        {% set image =  (image_article_directory ~ '/' ~ article.image) %}

    {% endif %}

    {{ include('common/header.html.twig', {'asset' : 'assets/img/bg-blog.jpg', 'alt' : 'header_blog', 'title' : article.title}) }}
    {{ include('common/breadcrumb.html.twig', {'breadcrumb' : breadcrumb }) }}
    <div class="container margin-t">
        <div class="row">
            <div class="col s12">
                <div class="center">
                    <img src="
                        {% if article.image is null %}
                            http://via.placeholder.com/750x350
                        {% else %}
                            {{ image_article_directory }}/{{ article.image }}
                        {% endif %}
                    " alt="article_" class="responsive-img">
                </div>
                <div>
                    {{ article.content|raw }}
                </div>
                <p class="center margin-b margin-t">{{ article.user.lastname }} {{ article.user.firstname }} - {{ article.publishingDate|date("d/m/Y") }}</p>
            </div>
        </div>
    </div>
{% endblock %}

templates/blog/editArticle.html.twig
{% extends 'base.html.twig' %}
{% form_theme form 'materialize_layout.html.twig' %}

{% block title %}Éditer article - NAO{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <script src="{{ asset('assets/js/tinymce/tinymce.min.js') }}"></script>
    <script>
        tinymce.init({
            selector:'.tinymce',
            height: 400,
            plugins: 'image link lists advlist autolink media',
            menubar: false,
            toolbar: ' undo redo | formatselect | bold italic underline strikethrough | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | cut copy paste | link image media'
        });
    </script>
{% endblock %}

{% block body %}
    {{ include('common/header.html.twig', {'title' : 'Editer article'}) }}
    {{ include('common/breadcrumb.html.twig', {'breadcrumb' : breadcrumb }) }}
    <div class="container margin-t">
        {{ form_start(form) }}
        {{ form_row(form.title) }}
        {{ form_row(form.content) }}
        {% if form.image is defined %}
            {{ form_widget(form.image) }}
        {% endif %}
        {% if form.delete_image is defined %}
            {{ form_widget(form.delete_image) }}
        {% endif %}

        <div class="row center margin-t margin-b">
            {% if form.publish is defined %}
                {{ form_widget(form.publish, { 'attr' : { 'class' : 'btn-round btn-brown'}}) }}
            {% endif %}
            {{ form_widget(form.save, { 'attr' : { 'class' : 'btn-round btn-brown'}}) }}
            {{ form_widget(form.delete, { 'attr' : { 'class' : 'btn-round btn-brown'}}) }}
        </div>

        {{ form_end(form) }}
    </div>
{% endblock %}

templates/blog/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Blog - NAO{% endblock %}

{% block body %}
    {{ include('common/header.html.twig', {'asset' : 'assets/img/bg-blog.jpg', 'alt' : 'header_blog', 'title' : 'Blog'}) }}
    {{ include('common/breadcrumb.html.twig', {'breadcrumb' : breadcrumb }) }}
    <div class="row container margin-t">
        {% for article in articles%}
        <div class="col s12 l4">
            <div class="card card-blog">
                <div class="card-image">
                    <div class="center">
                        <img src="
                        {% if article.image is null %}
                            http://via.placeholder.com/750x350
                        {% else %}
                            {{ image_article_directory }}/{{ article.image }}
                        {% endif %}
                    " alt="article_">
                    </div>
                </div>
                <div class="card-bottom">
                    <div class="card-content">
                        <p class="center card-title card-title-blog">{{ article.title }}</p>
                        <p class="center card-author">{{ article.user.lastname }} {{ article.user.firstname }} - {{ article.publishingDate|date("d/m/Y") }}</p>
                        <p>
                            {{ article.content|slice(0,250)|striptags|raw }}...
                        </p>
                    </div>
                    <div class="center card-action">
                        <a href="{{ path('blog-article', {'id': article.id}) }}" class="btn btn-round btn-teal">Lire l'article</a>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="center-align">
        {{ include('common/pagination.html.twig', {'paginaion' : pagination}) }}
    </div>
{% endblock %}

templates/blog/manageBlog.html.twig
{% extends 'base.html.twig' %}

{% block title %}Gérer les articles - NAO{% endblock %}

{% block body %}
    {{ include('common/header.html.twig', {'title' : 'Gérer les articles'}) }}
    {{ include('common/breadcrumb.html.twig', {'breadcrumb' : breadcrumb }) }}
    <div class="container margin-t">
        {% for i in 0..1 %}
            <div class="row">
                {% for j in 0..2%}
                    {% set k = 3*i+j %}
                    {% if articles|length > k %}
                        <div class="col s12 l4">
                            <div class="card">
                                <div class="card-content card-custom">
                                    <div class="row">
                                        <div class="center">
                                            <img src="
                            {% if articles[k].image is null %}
                            http://via.placeholder.com/750x350
                            {% else %}
                                {{ image_article_directory }}/{{ articles[k].image }}
                            {% endif %}
                            " alt="article_" class="height-img">
                                        </div>
                                        <div class="col s9">
                                            <p>{{ articles[k].title }}</p>
                                            <p>
                                                {{ articles[k].modificationDate|date("d/m/Y") }} - {% if not articles[k].status %}Brouillon{% else %}Publié{% endif %}
                                            </p>
                                        </div>
                                        <div class="col s3">
                                            <a href="{{ path('edit-article', {'id_article': articles[k].id}) }}" class="btn-floating btn-large"><i class="material-icons">add</i></a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endif %}
                {% endfor %}
            </div>
        {% endfor %}
    </div>
    <div class="row">
        <div class="col s12">
            {{ form_start(form) }}

            <div class="center-align">
                {{ form_widget(form.addArticle, { 'attr' : { 'class' : 'btn-round btn-teal'}}) }}
            </div>

            {{ form_end(form) }}
        </div>
    </div>
    <div class="row center">
        {{ include('common/pagination.html.twig', {'paginaion' : pagination}) }}
    </div>
{% endblock %}