src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Constraints\Date;
use Symfony\Component\Validator\Constraints\DateTime;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @UniqueEntity(fields="email", message="Cette email est déjà utilisé", groups={"registration"})
 * @UniqueEntity(fields="username", message="Ce nom d'utilisateur est déjà utilisé", groups={"registration"})
 */

class User implements UserInterface, \Serializable

{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;


    /**
     * @ORM\Column(type="json")
     */
    private $roles;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $lastname;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $firstname;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $username;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $password;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $registration_date;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $date_of_birth;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $gender;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $token;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $token_date;

    /**
     * @Assert\Image(
     *     allowLandscape = false,
     *     allowPortrait = false,
     *     minHeight=300,
     *     minWidth=300,
     *     maxHeight=300,
     *     maxWidth=300
     *)
     */
    private $new_image;

    private $new_password;

    /**
     * @return mixed
     */
    public function getNewPassword()
    {
        return $this->new_password;
    }

    /**
     * @param mixed $new_password
     */
    public function setNewPassword($new_password): void
    {
        $this->new_password = $new_password;
    }

    /**
     * @return mixed
     */
    public function getNewImage()
    {
        return $this->new_image;
    }

    /**
     * @param mixed $new_image
     */
    public function setNewImage($new_image): void
    {
        $this->new_image = $new_image;
    }


    public function getId()
    {
        return $this->id;
    }

    /**
     * @return array roles
     */
    public function getRoles(): array
    {
        $roles = $this->roles;

        // In order to be sure that a user always has at least 1 role.
        if (empty($roles)) {
            $roles[] = 'ROLE_USER';
        }
        return array_unique($roles);
    }

    /**
     * @param array $roles
     */
    public function setRoles(array $roles): void
    {
        $this->roles = $roles;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getRegistrationDate()
    {
        return $this->registration_date;
    }

    public function setRegistrationDate($registration_date): self
    {
        $this->registration_date = $registration_date;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getDateOfBirth(): ?\DateTimeInterface
    {
        return $this->date_of_birth;
    }

    public function setDateOfBirth(?\DateTimeInterface $date_of_birth): self
    {
        $this->date_of_birth = $date_of_birth;

        return $this;
    }

    public function getGender(): ?bool
    {
        return $this->gender;
    }

    public function setGender(?bool $gender): self
    {
        $this->gender = $gender;

        return $this;
    }

    public function getToken(): ?string
    {
        return $this->token;
    }

    public function setToken(?string $token): self
    {
        $this->token = $token;

        return $this;
    }

    public function getTokenDate(): ?\DateTimeInterface
    {
        return $this->token_date;
    }

    public function setTokenDate(?\DateTimeInterface $token_date): self
    {
        $this->token_date = $token_date;

        return $this;
    }

    public function getSalt(): ?string
    {
        return null;
    }

    public function eraseCredentials(): void
    {
        // We do not need this method at the moment but it is mandatory because it is included in the UserInterface interface
        // $this->plainPassword = null;
    }

    public function serialize(): string
    {
        return serialize([$this->id, $this->username, $this->password]);
    }

    public function unserialize($serialized)
    {
        [$this->id, $this->username, $this->password] = unserialize($serialized, ['allowed_classes' => false]);
    }

}

templates/back/add_observation.html.twig
{% extends 'base.html.twig' %}
{% form_theme form 'materialize_layout.html.twig' %}

{% block title %} Ajout Observation {% endblock %}


{% block body %}

    <div class="center">
        <h1 class="header-text">Ajouter une observation</h1>
    </div>
    <div class="margin-bottom">
        {{ include('common/breadcrumb.html.twig', {'breadcrumb' : breadcrumb }) }}
    </div>
{{ form_start(form) }}
    <div class="container center" id="observation-map">
        <div class="row">
            <div class="col s12" id="bloc-map">
                <div id="map-observation">

                </div>
            </div>
        </div>
        <div class="row form-map">
            <div class="col s12 m10 offset-m1 l4">
                {{ form_row(form.address) }}
            </div>
            <div class="col s12 m10 offset-m1 l4">
                {{ form_row(form.latitude) }}
            </div>
            <div class="col s12 m10 offset-m1 l4">
                {{ form_row(form.longitude) }}
            </div>
        </div>
        <button id="hide" class="btn btn-round btn-brown margin-bottom-light" type="button">Enregistrer les infos</button>
    </div>
    <div class="container center">

        <p>
            *Champs obligatoires
        </p>

        <div class="row">
            <div class="col s12 m6" id="observation-autocomplete">
                <div class="row">
                    <div class="input-field col s12">
                        <input type="text" id="autocomplete-input"  @input="search" class="autocomplete" autocomplete="off">
                        <label for="autocomplete-input">Nom de l'espèce</label>
                    </div>
                </div>
                {{ form_row(form.bird) }}
            </div>

            <div class="col s12 m6" >
                <div class="row">
                    <div class="input-field col s12">
                        <input type="text" id="location-input" autocomplete="off">
                        <label for="location-input">Lieu d'observation*</label>
                    </div>
                </div>
            </div>

        </div>
        <div class="row">
            <div class="col s12 m6" >
                <div class="row">
                    <div class="input-field col s12">
                        <input type="text" class="datepicker " id="observation-date-input" autocomplete="off">
                        <label for="observation-date-input">Date d'observation*</label>
                    </div>
                </div>
            </div>
            <div class="col s12 m6" >
                <div class="row">
                    <div class="input-field col s12">
                        <input type="text" class="timepicker" id="observation-time-input" autocomplete="off">
                        <label for="observation-time-input">Heure d'observation*</label>
                    </div>
                </div>
            </div>
            <div class="col s12" id="date-div">
                {{ form_widget(form.observation_date) }}
            </div>
        </div>
        <div class="row">
            <div class="col s12">
                {{ form_row(form.image, {
                    'label_attr': {'class': 'file-label'}
                }) }}
            </div>
        </div>
        <button class="btn btn-round btn-brown margin-b" type="submit"> Envoyer l'observation</button>
        {{ form_end(form) }}
    </div>

{% endblock %}

{% block autocomplete %}
    <script src="{{ asset('build/app.js') }}"></script>
{% endblock %}

templates/back/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Profil - NAO{% endblock %}

{% block body %}
    <div class="valign-wrapper grey lighten-3 border-teal-bottom full-height padding-top padding-bottom">
        <div class="center-block full-width">
            <div class="row">
                <div class="col offset-s2 s8 offset-l5 l2">
                    <img src="{% if user.image is same as(null) %}{{ asset('assets/img/profile-placeholder.jpg') }}{% else %}{{ image_profile_directory }}/{{ user.image }}{% endif %}" alt="Photo_profil" class="responsive-img circle"/>
                </div>
            </div>
            <div class="row">
                <h1 class="center lighter">{{ user.username }}</h1>
            </div>
            {% if app.user.id is same as(user.id) %}
                <div class="row center-align">
                    {% if is_granted('ROLE_PARTICULAR') or is_granted('ROLE_NATURALIST') or is_granted('ROLE_ADMIN')%}
                        <a href="{{ path('ajout_observation') }}" class="btn btn-round btn-brown">Ajouter observation</a>
                        <a href="{{ path('mes_observations') }}" class="btn btn-round btn-brown">Mes observations</a>
                    {% endif %}
                    {% if is_granted('ROLE_ADMIN') %}
                        <a href="{{ path('waiting-observation') }}" class="btn btn-round btn-brown">Observation en attente</a>
                    {% endif %}
                    {% if is_granted('ROLE_EDITOR') or is_granted('ROLE_ADMIN') %}
                        <a href="{{ path('gerer-articles') }}" class="btn btn-round btn-brown">Gérer les articles</a>
                    {% endif %}
                </div>
            {% endif %}
            <div class="row center-align">
                <a class="section scrollspy link-black" href="#"><i class="medium material-icons">expand_more</i></a>
            </div>
        </div>
    </div>

    {% if app.user.id is same as(user.id) and is_granted('ROLE_NATURALIST') %}
        {% set col_width = 4 %}
    {% else %}
        {% set col_width = 6 %}
    {% endif %}

    <div class="">
    <div class="row margin-t link-teal">

        {#---- Présentation ----#}
        <div class="col s12 l{{ col_width }}">
            <div class="card-panel card-profile">
                <div class="card-title valign-wrapper ">
                    <h5 class="center-block lighter">
                        Présentation
                    </h5>
                </div>
                <div class="card-content">
                    <div class="col s12">{{ user.lastname|upper }} {{ user.firstname }}</div>
                    <div class="col s12">{{ user.email }}</div>
                    <div class="col s12">Né le {{ user.dateOfBirth|date("d/m/Y") }}</div>
                    <div class="col s12">{% if user.gender == true %}Masculin{% else %}Feminin{% endif %}</div>
                    <div class="col s12">Inscrit le {{ user.registrationDate|date("d/m/Y") }}</div>
                </div>
            </div>
        </div>

        {#---- Dernières activités ----#}
        {% if is_granted('ROLE_PARTICULAR') or is_granted('ROLE_NATURALIST') or is_granted('ROLE_ADMIN') %}
        <div class="col s12 l{{ col_width }}">
            <div class="card-panel card-profile">
                <div class="card-title valign-wrapper">
                    <h5 class="center-block lighter">
                        Dernières activités
                    </h5>
                </div>
                <div class="card-content">
                    {% for observation in observations %}
                        <div class="col s12">
                            <span>Observation : </span><br>
                            <a href="{{ path('view_observation', { "id" : observation.id}) }}">
                                {% if observation.bird == null %}
                                    Espèce non connue
                                {% else %}
                                    {{ observation.bird.vernacularName }}
                                {% endif %}
                            </a><i> (
                            {% if observation.bird == null %}
                                -
                            {% else %}
                                {{ observation.bird.lbName }}
                            {% endif %})</i>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
        {% endif %}
        {#---- Validation ----#}
        {% if is_granted('ROLE_NATURALIST') or is_granted('ROLE_ADMIN') %}
        <div class="col s12 l{{ col_width }}">
            <div class="card-panel card-profile">
                <div class="card-title valign-wrapper">
                    <h5 class="center-block lighter">
                        Validation d'espèces
                    </h5>
                </div>
                <div class="card-content">
                    {% for validation in validations %}
                        <div class="col s12">
                            <span>Observation validée : </span><br>
                            <a href="{{ path('view_observation', { "id" : validation.id}) }}">{{ validation.bird.vernacularName }}</a><em> ({{ validation.bird.lbName }})</em>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
        {% endif %}

        {#---- Article ----#}
        {% if is_granted('ROLE_EDITOR') or is_granted('ROLE_ADMIN') %}
        <div class="col s12 l{{ col_width }}">
            <div class="card-panel card-profile">
                <div class="card-title valign-wrapper">
                    <h5 class="center-block lighter">
                        Article
                    </h5>
                </div>
                <div class="card-content">
                    {% for article in articles %}
                        <div class="col s12">
                            <span>Article publié : </span><br>
                            <a href="{{ path('blog-article', { "id" : article.id}) }}">{{ article.title }}</a>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
        {% endif %}

    </div>
    </div>

    {% if app.user.id is same as(user.id) %}
        <div class="row center margin-t margin-b">
            <a href="{{ path('modify-profile') }}" class="btn btn-round btn-brown">Modifier le profil</a>
            {% if is_granted('ROLE_PARTICULAR') %}
                <a href="{{ path('demand') }}" class="btn btn-round btn-brown">Demande naturaliste</a>
            {% endif %}
            {% if is_granted('ROLE_NATURALIST') %}
                <a href="{{ path('waiting-observation') }}" class="btn btn-round btn-brown">Observation(s) en attente</a>
            {% endif %}
            {% if is_granted('ROLE_ADMIN') %}
                <a href="{{ path('manage-user') }}" class="btn btn-round btn-brown">Gérer Utilisateur </a>
                <a href="{{ path('waiting-demand') }}" class="btn btn-round btn-brown">Certifier un naturaliste</a>
            {% endif %}
            <a href="{{ path('security_logout') }}" class="btn btn-round btn-brown">Déconnexion</a>
        </div>
    {% endif %}
{% endblock %}

templates/back/manage_user.html.twig
{% extends 'base.html.twig' %}

{% block title %}Gérer utilisateur{% endblock %}
{% block body %}

    <div class="center">
        <h1 class="header-text">Gérer utilisateur</h1>
    </div>
    <div class="margin-bottom">
        {{ include('common/breadcrumb.html.twig', {'breadcrumb' : breadcrumb }) }}
    </div>
    <div class="row container">
        {% for user in users %}
            <div class="col s12 m6 l3">
                <div class="card">
                    <div class="">
                        <img src="{% if user.image is null%}{{ asset('assets/img/profile-placeholder.jpg') }}{% else %}{{ image_profile_directory }}/{{ user.image }}{% endif %}" alt="photo_profil" class="responsive-img">
                    </div>
                    <div class="card-content center">
                        <div class="card-title">{{ user.lastname|upper }} {{ user.firstname }}</div>
                        <p>Inscrit le {{ user.registrationDate|date("d/m/Y") }}</p>
                    </div>
                    <div class="center card-action">
                        <a href="{{ path('profil', {'id': user.id}) }}" class="btn btn-round btn-teal">Voir plus</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    <div class="row">
        <div class="center-align">
            {{ include('common/pagination.html.twig', {'paginaion' : pagination}) }}
        </div>
    </div>
{% endblock %}

templates/back/modify_profile.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier mon profil - NAO{% endblock %}

{% block body %}
    {{ include('common/header.html.twig', {'title' : 'Modifier mon profil'}) }}
    <div class="container">
        {{ form_start(form) }}
        <div class="row">
            <div class="col offset-s2 s8 offset-l5 l2">
                <img src="{% if user.image is same as(null) %}{{ asset('assets/img/profile-placeholder.jpg') }}{% else %}{{ image_profile_directory }}/{{ user.image }}{% endif %}" alt="profile" class="responsive-img circle">
            </div>
        </div>
        <div class="row margin-b">
            <div class="col s12 offset-l4 l4">
                {{ form_help(form.newImage) }}
                {{ form_row(form.newImage) }}
            </div>
        </div>
        <div class="row">
            <div class="col s12 l6">
                {{ form_row(form.lastname) }}
            </div>
            <div class="col s12 l6">
                {{ form_row(form.firstname) }}
            </div>
        </div>
        <div class="row">
            <div class="col s12 l6">
                {{ form_row(form.email) }}
            </div>
            <div class="col s12 l6">
                {{ form_row(form.date_of_birth) }}
            </div>
        </div>
        <div class="row">
            <div class="col s12 l6">
                {{ form_row(form.gender) }}
            </div>
        </div>
        <div class="row">
            <div class="col s12 l6">
                {{ form_row(form.username) }}
            </div>
            {#<div class="col s12 l6">#}
                {#{{ form_row(form.password) }}#}
            {#</div>#}
        </div>
        <div class="row">
            <div class="col s12 l6">
                {{ form_row(form.newPassword.first) }}
            </div>
            <div class="col s12 l6">
                {{ form_row(form.newPassword.second) }}
            </div>
        </div>
        <div class="center-align">
            {{ form_widget(form.submit, { 'attr' : { 'class' : 'btn-round btn-brown'}}) }}
        </div>
        {{ form_end(form) }}
    </div>
{% endblock %}

templates/back/my_observations.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mes observations{% endblock %}
{% block body %}

    <div class="center">
        <h1 class="header-text">Mes observations</h1>
    </div>
    <div class="margin-bottom">
        {{ include('common/breadcrumb.html.twig', {'breadcrumb' : breadcrumb }) }}
    </div>
    <div class="container-my-observations">
        <div class="row">
        {% for observation in observations %}
            <div class="col s12 m6 l4">
                <div class="card">
                    <div class="card-image">
                        <img src="{{ image_observation_directory }}/{{ observation.image }}">

                        <a class="btn-floating btn-large halfway-fab waves-effect waves-light maroon"  href="{{ path('view_observation', {'id': observation.id}) }}"><i class="material-icons">add</i></a>
                    </div>
                    <div class="card-content">
                        <span class="title-card-my-observations">
                            {% if observation.bird == null %}
                                Espèce non connue
                            {% else %}
                                {{ observation.bird.vernacularName }}
                            {% endif %}
                        </span>
                        <p class="content-card-my-observations">{{ observation.addingDate|date("d/m/Y") }} -
                            {% if  observation.status == false %}
                                En cours de validation
                            {% else %}
                                Observation validée
                            {% endif %}
                        </p>
                    </div>
                </div>
            </div>
        {% endfor %}
        </div>
    </div>
    <div class="row">
        <div class="center-align">
            {{ include('common/pagination.html.twig', {'paginaion' : pagination}) }}
        </div>
    </div>
{% endblock %}

templates/back/waiting_observation.html.twig
{% extends 'base.html.twig' %}

{% block title %}Observation en attente - NAO{% endblock %}

{% block body %}
    {{ include('common/header.html.twig', {'title' : 'Observations en attente'}) }}
    {{ include('common/breadcrumb.html.twig', {'breadcrumb' : breadcrumb }) }}
    <div class="row container margin-t">
        {% for observation in observations %}
            <div class="col s12 l4">
                <div class="card card-wait-obs">
                    <div class="card-image">
                        <div class="center">
                            <img src="
                        {% if observation.image is null %}
                            http://via.placeholder.com/750x350
                        {% else %}
                            {{ image_observation_directory}}/{{ observation.image }}
                        {% endif %}
                    " alt="article_">
                        </div>
                    </div>
                    <div class="card-bottom">
                        <div class="card-content">
                            <p class="center card-title card-title-blog">
                                {% if observation.bird == null %}
                                    Espèce non connue
                                {% else %}
                                    {{ observation.bird.vernacularName }}
                                {% endif %}
                            </p>
                            <p class="center card-author">Observation envoyée le {{ observation.addingDate|date("d/m/Y") }}</p>
                        </div>
                        <div class="center card-action">
                            <a href="{{ path('view_observation', {'id': observation.id}) }}" class="btn btn-round btn-teal">Voir l'observation</a>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    <div class="row center">
        {{ include('common/pagination.html.twig', {'paginaion' : pagination}) }}
    </div>
{% endblock %}